# using NodePort this time until I get my domain back
service:
  type: NodePort
  port: 8080
  nodePort: 30080

livenessProbe: {}
readinessProbe: {}

tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  config:
  secrets:
    GABS_DATABASE_URL: "opora-db"
    GABS_REDIS_URL: "opora-db-redis"